language: python
services:
- docker
python:
- '2.7'
install:
- make deps
script:
- make test
- make lint
- make docker_build
- make docker_push
env:
  global:
    secure: IcuivAIEDrvdWzI4OmCIPynLnRj3xQiuhNpBIcBN78jV8SDRgErqIlH5XKUjNRPM6h68PTBSnzSvoAAjgkm+VpMJAr+idY7B9+L3HSDGBvPZXeb0g9Kh8iB0CkLW5ptIgdaVQV8wmtvKZVClymDn2gllsWt7kRHMOj2BFLXPS2b+ExHlPrDm5Sdg/q0+UfORrtOX8oTc31z4bLsuMoj5M4i1NEB6W41ObIwIUMUQIi94D8w3zDW2pquaZ/aSQMBuwdmd7KkjBCXA4aVaohYHrwL0+BWhdpsBwaFT1lmivxRcnw3t3Tpebc4rJo75dkAGMp8z+nqfniSpM54PgsYiGqnLi+RS1dOxgU4sY4m5wAHZ6Abqe4tUmREYHwLGJ+hy4f+AshQfiLEjnvr1ghfjI3deKYs1T7+a1mJspEsHdR8ge+F06xQVlaf/eTv1EIYOiD886ql2oVOipCEexSHA6ZmLoyeiafn8PF3yZbZp/qojzhL+5/6khnbNuTLtcpQF914/1TDjgZQqjzlx3Mdi+Gk1rCDTfmyzId2XXPyXjwj0juYBjsrfRbjh3Nt01bVgDYetMMIWnjjrvLmY1jiYS+9Jut0aQvHpCEuSE66hHU2wcZOOJN3vFIIV8eofDHD94nIzwmzoL9tjQV6sIbm2OvbEpvQFK8rssgdHMuRWnXY=
