language: python
services:
- docker
python:
- '2.7'
install:
- make deps
script:
- make test
- make test_xunit
- make lint
- make docker_build
- make docker_push
deploy:
  provider: heroku
  app: peaceful-shore-78285
  api_key:
    secure: M9c/8MEDOiWvntWsS6a2qbJSLaq1Rz9fuJWpalFWSiukPgCOPwpDhulcaDnp2vU2wBwpfTMoYf+uyrEoMhhksVC2ZCLuY5dTRtwT058xXxQj2Y08gxGhRzIo5ETjD9b/pwOmHAJJ5bS9Lw+rG8MFv1/CSwhxoV99xrA9DEKU167YwlAmH8R3eEHIHfIN7/9qtPIQjwK5+YposYzEIcXdyAFmFb6dw2TbH48bgxA5qNhckdvs4bjDRVu8j6iEzXruQWfx/84O5TZLbE8O8OmbhkPgy96BBM28BUxXVpmDv2YByU3Lq15mvH47vq9tY8Yw0y+2iqlfe8zPDbEdbctDgdo23WvtgbV9LbOO6kyMdPxYl5MXJEG1mdiIIIdIaq9CG7xbe0a4Sm8SYByKyMW7uQSMSSeRxHJg4BtJu/GJ6yCtPWcX6QDzqtpXzcYcgFtkuDIC2P0wUpTlII6ayFhcvWrorSuHcA7f/4AJtOOn27vQCsYA+HIOy9g/5yUEjR2i89eaTZXYBqmrJ/dubeTbexhfarxC0DEWbJMqs2GIZwpHUA/hKAZlSslPd/AQ3r3XETokqX+bsTtvu0n6PzqkFrAAZmJ8HcLlMrScIreTnmX6c96UrAr2jVldMJeCGrU6IycADDhEX517Q5nVW2nDRKs9HFb9pBwD45PCxLwWAqw=
env:
  secure: Hf0qgEYWlXIodCQoXXlHeOXDGpAbtB/KYnVAUHcYVARUVEHTASNj11NgZQA9FiqwnDiMOlEDzVKGdIrQdCirZHvtR4h/BezHj6Ot5O5A3kPDmlmFbBMR3tt1Fsa+b6WFYegEUVcPwp9QbrqYVAqH6GAArFy7SRRQQYZ1Si7njZ2+WPh736Qq/+CjUvXqv7VP1Tt3mybjr5kvrvGHCjZZyYctY+/15z3FolyrMZJmLTs1Cx9JGacMB7c9yikSaHHAaeTrNTmFfN9SxykrewJTlw7wjqhlSOU4Ob0gUcfx+6pjmWrsdLpqzTesP61qBfvF4M0hO8ymAYEzMfsx4SZufCXNJp/jzea3aeMh4WYoBNE3rw7wdPGY4tMJ833NJyDz4LGhnFCSZ5g92I/VJra49soyXrcA3ovz2GAoM6lpZIc51DKgEEuN+/x52ynXRDiq5JGwVVv8OH4Za1aHIl3A9b4Id71tjTC5+XD7vdfiI2tycT8dZd8f2Tu0a7+udCXZD9+s0GZwFd2/Xbu03tn52wA+R11fs9HfPqdagokl8V2s0HzK9uDAAlIUpxdCdS2sOMIkRVUaqybx5lm2i0g8AHbC3wm580/JKmZcMcKLUbxrI+nGRoTIx3AzyA1MRVOVc1FBokeEXGTH69Jxjnz1BBrJInGwc0pa8fw1vtP9mhk=
