language: python
services:
- docker
python:
- '2.7'
install:
- make deps
script:
- make test
- make lint
- make docker_build
- make docker_push
env:
  secure: P9S14X+K9j7s4vojf4wzVsulNf4xTolj09m4M4VyZksrDuqpMPOIentWUUZ8W+eiRU+ThSc3TyHMoTaI1R8N3CX8IvtGv8+gM8yajRI+DIRnmW4gZhATsVsUuNfCrlAtyBnOL0P/eVno57jXSeDjhEgnnoagYzk4h1INvFBYFQmVZ3x8x834lVIAinGJk2JAMQJukzJX7+2t2Myz/KHrktVfuER+lwyoxitxfgcU50E+kcKOgsllps8dLBSrnLzMDvWiZTodKBZ3hMHEC3vlquhJKEMtJiqd2oE1i/Czw/y6aOVRM4i7ccf62mXlqsBCv1VAp1RjkxWji3cs1xZ9r/ASc//16OgPZjHCiKSC3tX9Z4gR9sk77d+6u9z4nXLFSstE8xi7Xm6EZDcejdVtugwjoDmOE8enIhJ2eNK2UEkajg3FCB0xqbvX3y3uH6XgnsMgy+mwSgzeHK6FMfqGMXuHiqAHmvfMChTD8v4Rz0lkyJEHKoqq1n9uxI5e/L2lR0d2fLwNCn1zpVa2CBC5IVjpHlKVv3EAf+rLNnrqiwQ1swGRr1ZwaRmiZCLaZ9k32EDoBTKpL9WPAzE4ogqTLfNfN0f5yNN08RT9LVStfM9MIC0tUSIZvsP9vjcax6dX9nwCloauBV3xX5XZ6lotpVL4wcWJ02w6GrM04KCFcjc=
