language: python
services:
- docker
python:
- '2.7'
install:
- make deps
script:
- make test
- make test_xunit
- make lint
- make docker_build
- make docker_push
deploy:
  provider: heroku
  app: peaceful-shore-78285
  api_key:
    secure: cXFDLruyJBW4Fr92rw5Mw+a5kfeqcuS5aSC67EeahTt/wGUZVo/YlipE3mN9wbCw4zn78SHE+OXOA7SfvurT5djOJqvIyBrAEYwvwH6YbfL66oHBtL9ODtEDzRqDhWuXuaoO6Vvia2vmUpedldNbClIKijChmsOLi+vAJYMQNp0MZv8oWQm3X5mAkCsrUi6c80hyUVmZaWrN0teheTVi66Gr3culEW4j2zhrRV3Oiy7LU/N6q0kUlx+A3PKwEN6r1mlY2vDEq//FNEwYdvVt4QqfFQZujeESHoyuQiqVf5KvwpiAg/DR91LD3ZzkLQMXTgpkF2H3V75PfHEclXlRWYLWEd1x+1U489KHTmxs9QZjtsTXdxk5EaW28A92yuGP4AJrL5iLsUPVobRIOxpiShOPnM8qUX2or0qGgFpKa9vQswUEI4RMb738IAw6KYDxG6PwvureOB5XTHqZropfWsLb04FrS/vLU4Cbad67tZ1OnewNXDMZdPbPKn2eF0fNfi/cplONM5vHgwYWrMxOpeiUPiWKrH2xRecRh5aOYQ7jFIF5BrdCZk8N+Q03i1N+YfN/mOIEexIIc+K2HmamgXtPXOM+qP1FnzzSgF0McNRhOGJlx3E/cx5/hCCq6qGY19TENd62I2A861/PfJnvpcUriPu+HOUoeZypDZ6fz7E=
env:
  secure: Hf0qgEYWlXIodCQoXXlHeOXDGpAbtB/KYnVAUHcYVARUVEHTASNj11NgZQA9FiqwnDiMOlEDzVKGdIrQdCirZHvtR4h/BezHj6Ot5O5A3kPDmlmFbBMR3tt1Fsa+b6WFYegEUVcPwp9QbrqYVAqH6GAArFy7SRRQQYZ1Si7njZ2+WPh736Qq/+CjUvXqv7VP1Tt3mybjr5kvrvGHCjZZyYctY+/15z3FolyrMZJmLTs1Cx9JGacMB7c9yikSaHHAaeTrNTmFfN9SxykrewJTlw7wjqhlSOU4Ob0gUcfx+6pjmWrsdLpqzTesP61qBfvF4M0hO8ymAYEzMfsx4SZufCXNJp/jzea3aeMh4WYoBNE3rw7wdPGY4tMJ833NJyDz4LGhnFCSZ5g92I/VJra49soyXrcA3ovz2GAoM6lpZIc51DKgEEuN+/x52ynXRDiq5JGwVVv8OH4Za1aHIl3A9b4Id71tjTC5+XD7vdfiI2tycT8dZd8f2Tu0a7+udCXZD9+s0GZwFd2/Xbu03tn52wA+R11fs9HfPqdagokl8V2s0HzK9uDAAlIUpxdCdS2sOMIkRVUaqybx5lm2i0g8AHbC3wm580/JKmZcMcKLUbxrI+nGRoTIx3AzyA1MRVOVc1FBokeEXGTH69Jxjnz1BBrJInGwc0pa8fw1vtP9mhk=
